### ISSUE TITLE
Fix Fq- and Fqbar-isomorphisms

### ISSUE THREAD

**Issue by j-kieffer** [defeo/hhs-keyex#16]
I think we need to be more precise about Fq- and Fqbar-isomorphism classes for curves (and isogenies).
For example, when we define Ell_q(O), do we want the Frobenius to be fixed as an element of O, and not only up to sign ?
 - If yes, then we do not allow quadratic twists; we are really working with Fq-isomorphism classes. lambda and mu are well defined.
 - If no, then we indeed manipulate Fqbar-iso classes, but then lambda and mu are only defined up to sign.

Any Fqbar-iso class contains two Fq-iso classes (at least when j\neq 0, 1728).
We can say that we will work with Fq-iso classes, and switching to the quadratic twist means switching to the 'twin' isogeny graph labelled with -lambda and -mu.
See also sec. 3.2, when we explain Vélu steps.

**Comment by abelian** [comment]
I started to hint at this in \S2.2.  I'd say we are really working over FF_q, but 

1. we can ignore the non-quadratic twists because those curves are never in our cryptosystems (class groups too small)
2. the graph of E and the graph of its twist are disjoint and isomorphic, so we don't mind identifying them (using j-invariants as vertex labels)
3. but in theory we're really on the graph of E at all times (except when we flip to the twist for algorithmic reasons, but then we flip straight back after that step anyway)

I don't think it'll be hard to explain that.

**Comment by abelian** [comment]
On this subject, we need to fix ElkiesStep, which at the moment is not at all guaranteed to return the right curve (we can easily end up on the twist, even when we should have been on E_1...)

**Comment by abelian** [comment]
...i.e. I assume that whatever the function in Line 3 of ElkiesStep is, it returns the right E_1 (not the twist) for either \lambda or \mu.  Then there are two issues:

1. Line 5 checks if it's \lambda; if so then we should directly return E_1 (rather than re-constructing E_1 or its twist from j_1 in Line 7).  
2. That leaves us with the case where our isogeny is for \mu instead; but then we need to need to check that the E_R we've chosen is the right one, and not the twist.  I'm not sure how we should do this (no cute tricks come immediately to mind)...  And while it doesn't particularly matter because we're just going to keep walking on j-invariants in the same direction once this first step is done, the final curve output by the walk will still possibly be in the twist graph component, which would mess up the following walk.

**Comment by j-kieffer** [comment]
Now algorithms return the correct twist, and Ell_q(\O) is correctly defined as a set of curves up to Fq-isomorphism.
